spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1049506829081-k460f1ppc8ac7j1emi1kpurd8ukccdrf.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          github:
            client-id: fb545a6af39283f29ef6
            client-secret: ce380baf56cc76c801f01765f41f8af3dba541cc
            scope:
            - user:email
            - read:user